#!/usr/bin/env bash
# This is a temp comment
((i=1))
while ((i<11))
 do
	 if ((i%8==0))
	 then
		 echo "good luck"
	 elif ((i%4==0))
	 then
		 echo "bad luck"
	 else
		 echo "Best School"
	 fi
	 ((i++))
 done
