#!/usr/bin/bash
# Very superstisious... Writing on the shell
((i=1))
while ((i<21))
do
 case "$i" in
	 4) echo 'bad luck in China'
		 ;;
	 8) echo 'good luck in China'
		 ;;
	 17) echo 'bad luck in Italy'
		 ;;
	 *) echo $"$i"
 esac
 ((i++))
done
